### ISSUE TITLE
Including full libv8 source?

### ISSUE THREAD

**Issue by noamross** [jeroen/V8#9] opened 2015-03-07 16:30 UTC
As V8 is written in C++, is there a reason the full source can't be included in the package, rather than requiring libv8 as a system dependency?  It seems the libv8 BSD-3 license would allow this.  Is it a CRAN issue?

**Comment by jeroenooms** [comment] 2015-03-07 18:29
It would be very hard to make it build on all platforms and require a lot of patching to make the v8 source code pass cmd check.

**Comment by eddelbuettel** [comment] 2015-03-07 23:32
Sah the tweet,  so allow me to chime in. 

Generally speaking we much prefer external libraries where available,  and preferably well maintained.   Including the source,  and dealing with per-ardchitecture/OS build issues is generally not a winning proposition. 

Now,  I say that as a Linux user.  On the Mac,  this may be harder,  and on that other OS...

**Comment by jeroenooms** [comment] 2015-04-19 06:21
I'm kind of changing my mind about this. Upstream V8 changes very quickly and is often not backward compatible with older versions. Different linux distributions ship different versions of libv8 which makes it very difficult to write an R package that will work on any system. In addition the static libraries on windows are quite painful as well because they depend on the version of the tool chain they were compiled with, which will be changing soon.

If there is a sensible way to bundle the libv8 source code with the package we should look into that. The problem is that libv8 is a pain to build:

> V8 is built with the help of GYP. GYP is a meta build system of sorts, as it generates build files for a number of other build systems. How you build therefore depends on what "back-end" build system and compiler you're using. 

However maybe we don't need all of this crazyness to support R.

**Comment by justa9** [comment] 2015-05-19 05:10
Another unfortunate collateral is that using the (already compiled) libv8 breaks support for V8 on Windows XP.

The V8 package is successfully compiled from source, but breaks just at "testing if installed package can be loaded" step as it cannot load the resulting DLL (V8.DLL). The error is "LoadLibrary failure:  The specified procedure could not be found" and it refers to msvcrt.dll

**Comment by daattali** [comment] 2015-11-24 22:53
I can't chime in about the technical details of how easy it would be or how to do this, but I just want to voice another vote for seeing this happen.  I use `V8` in my package and there are users who can't use my package because of that.  If it's any help, I wouldn't really care about the exact version, just having any version will be just fine.

Also, if Windows XP is the only OS that will have problems including libv8, is that so bad?  It still means all other OS (which I assume is most users) will benefit, and only the small fraction of people on XP won't. But it's not like they will regress.  That's my understanding at least.

**Comment by jeroenooms** [comment] 2015-11-24 22:54
Why can't users install V8? Which OS do they use? It builds on all platforms: https://cran.r-project.org/web/checks/check_results_V8.html

**Comment by daattali** [comment] 2015-11-24 22:57
@oganm has been having problems with it, I think he's on CentOS.  And I think when I first tried installing it on an ubuntu machine, I actually had to manually install libv8 (installing the `V8` R package did not take care of it for me), but I could be wrong.

**Comment by jeroenooms** [comment] 2015-11-24 23:02
Indeed you need to `apt-get install libv8-dev` on Ubuntu or `yum install v8-devel` on Fedora/CentOS. This holds for many packages because Linux works with shared libraries. If you use linux you should be able to figure that out I think. 

On CentOS you can easily grab `v8-devel` from [EPEL](https://fedoraproject.org/wiki/EPEL).

**Comment by daattali** [comment] 2015-11-24 23:28
Ah ok, I didn't realize this was common for other R packages as well. But for Windows and OSX users, `V8` should install just fine then. Thanks

**Comment by eddelbuettel** [comment] 2015-11-25 00:53
Which is what we said earlier:
- it is common (as all Linux distro use shared libraries, as does AFAIK brew)
- it is better (as you library updates when the upstream libraries updates as opposed to when your CRAN package maintainer decides too---flipside is that this assumes stable APIs and libraries)
- it is faster: when you have system libraries you do not need to recompile these libs on every package update or test.

In R land we are a little orthogonal in that we tend to think about self-contained packages. But if you look more closely LOTS of them use (and require) system level libraries.  In some cases we support both--see [nloptr](http://cran.rstudio.com/package=nloptr)  comes to mind, and I helped make that current dual approach happen.

**Comment by oganm** [comment] 2015-11-25 20:38
The problem I had was being unable to install libV8 to centos 5.11. v8-devel package doesn't seem to be available for that version.

**Comment by jeroenooms** [comment] 2015-11-25 21:00
CentOS 5 is really old, libv8 might not even build on that. Which gcc version does that have?

**Comment by oganm** [comment] 2015-11-26 01:15
that'd be 4.1.2

**Comment by eddelbuettel** [comment] 2015-11-26 07:24
Rcpp alone needs _at least_ 4.6 ideally 4.8 or 4.9.  There is nothing we can do for you here.  

gcc 4.1.2 was [released in February 2007](https://gcc.gnu.org/releases.html). At some point you may want to join this decade.

**Closed** 2019-01-31 01:42 UTC
