### ISSUE TITLE
Fatal error on Arch Linux

### ISSUE THREAD

**Issue by jolars** [jeroen/V8#45] opened 2018-12-15 19:27 UTC
Running
```r
context <- V8::v8()
```
i get
```
# Fatal error in ../src/platform-linux.cc, line 776
# CHECK_EQ(0, result) failed
#   Expected: 0
#   Found: 22
```
and the R session crashes. I am running Antergos (Arch Linux) and have installed the v8-3.14 package.

Here is my session info:

```r
R version 3.5.1 (2018-07-02)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Antergos Linux

Matrix products: default
BLAS/LAPACK: /usr/lib/libopenblas_haswellp-r0.3.4.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=sv_SE.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=sv_SE.UTF-8   
 [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=sv_SE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=sv_SE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] V8_1.5        usethis_1.4.0

loaded via a namespace (and not attached):
[1] compiler_3.5.1 tools_3.5.1    parallel_3.5.1 fs_1.2.6       glue_1.3.0     curl_3.2       yaml_2.2.0     Rcpp_1.0.0     jsonlite_1.6
```

**Comment by jeroen** [comment] 2018-12-15 23:17
Dupe of https://github.com/jeroen/V8/issues/32

**Closed by jeroen** 2018-12-15 23:17 UTC

**Comment by jolars** [comment] 2018-12-16 09:09
@jeroen I don't see how this is a duplicate? I am getting a different error and am moreover using the aur PKGBUILD that was uploaded to fix the segfault error. Please consider reopening the issue.

**Comment by jeroen** [comment] 2018-12-16 10:59
Sorry but there is nothing I can do about this. You need to talk to the maintainer of the arch `v8-3.14` pkg. I am guessing you get the same error when using the `d8` command line tool?

**Comment by jolars** [comment] 2018-12-16 21:58
I understand. Running the d8 command line tool works perfectly fine, however.

**Comment by bringmethespoons** [comment] 2019-01-15 10:47
Got the same on Manjaro.

Session info:
`R version 3.5.2 (2018-12-20)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Manjaro Linux

Matrix products: default
BLAS: /usr/lib/libopenblasp-r0.3.4.so
LAPACK: /usr/lib/liblapack.so.3.8.0

locale:
 [1] LC_CTYPE=de_DE.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=de_DE.UTF-8        LC_COLLATE=de_DE.UTF-8    
 [5] LC_MONETARY=de_DE.UTF-8    LC_MESSAGES=de_DE.UTF-8   
 [7] LC_PAPER=de_DE.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=de_DE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.0           compiler_3.5.2       pillar_1.3.0        
 [4] plyr_1.8.4           bindr_0.1.1          prettyunits_1.0.2   
 [7] pkgbuild_1.0.2       tibble_1.4.2         gtable_0.2.0        
[10] lattice_0.20-38      pkgconfig_2.0.2      rlang_0.3.0.1       
[13] cli_1.0.1            parallel_3.5.2       mvtnorm_1.0-8       
[16] loo_2.0.0            bindrcpp_0.2.2       gridExtra_2.3       
[19] coda_0.19-2          dplyr_0.7.6          stats4_3.5.2        
[22] grid_3.5.2           tidyselect_0.2.5     inline_0.3.15       
[25] glue_1.3.0           R6_2.3.0             rethinking_1.80     
[28] processx_3.2.1       rstan_2.18.2         ggplot2_3.1.0       
[31] callr_3.1.0          purrr_0.2.5          magrittr_1.5        
[34] scales_1.0.0         ps_1.2.1             StanHeaders_2.18.0-1
[37] matrixStats_0.54.0   MASS_7.3-51.1        assertthat_0.2.0    
[40] colorspace_1.3-2     lazyeval_0.2.1       munsell_0.5.0       
[43] crayon_1.3.4        
`

**Comment by jethroppaPH** [comment] 2019-01-16 02:06
Is it okay to use the system package `v8` instead of the `v8-3.14` to use for the `V8` R package?

**Comment by jolars** [comment] 2019-02-25 20:18
I tried @jethroppaPH, but it doesn't work. The configure file protests and if it is overridden compilation of the V8 package fails.

I am still getting this error with the new version of V8 (2.0). As before, it works perfectly fine to use the command line tool.

**Comment by jeroen** [comment] 2019-02-25 20:43
Which version of libv8 are you compiling against? V8 2.0 should work with libv8 version 6 or 7...

**Comment by jolars** [comment] 2019-02-25 21:04
7.2

**Comment by jeroen** [comment] 2019-02-25 21:52
So what happens if you do `install.packages("V8")` in R?

**Comment by jolars** [comment] 2019-02-26 08:56
Running `install.packages()`  I get

```
Error: package or namespace load failed for ‘V8’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/home/johan/R/x86_64-pc-linux-gnu-library/3.5/V8/libs/V8.so':
  libc++.so: cannot open shared object file: No such file or directory
```

Forking and building from the github repo, I first get 

```
Oh dear. The wrong version of libv8 is installed on the system.
This package needs the 3.14 / 3.15 branch of libv8.
```

After fiddling with the `configure` file, however, the build process throws a myriad of compilation errors, such as

```
'ExternalArrayType' is not a member of 'v8'
```

**Comment by jeroen** [comment] 2019-02-26 08:58
That error message is gone in v8 2.0 so you are probably using an old version of the r package?

**Comment by jeroen** [comment] 2019-02-26 08:58
It looks like your system is missing libcxx

**Comment by jolars** [comment] 2019-02-26 12:34
> That error message is gone in v8 2.0 so you are probably using an old version of the r package?

Sorry, yes, I was using that. 

> It looks like your system is missing libcxx

Perhaps I am mistaken, but shouldn't libstdc++ (which I have) do just fine?

**Comment by jeroen** [comment] 2019-02-26 12:39
Your error message indicates that v8 was built with `libc++` instead of `libstdc++`...

**Comment by jolars** [comment] 2019-02-26 18:09
That would be strange considering that I don't even have libc++ installed. Anyway, thanks for the help but I reckon that there must be something wrong on my end so I won't be bothering you any more with it. I'll post if I get it working.

**Comment by jolars** [comment] 2019-03-07 07:04
For anyone else having issues with this, the following PKGBUILD solved my problem:

https://gist.github.com/JanMarvin/61ee142b21c394f5c67a55df4f960adc

**Comment by jeroen** [comment] 2019-03-07 08:53
How do we get that pkgbuild in arch?

**Comment by znmeb** [comment] 2019-03-07 09:49
@jeroen It's noted on the web page - https://aur.archlinux.org/packages/v8/

However, it crashed on my machine - I don't have time to troubleshoot it right now. It'll probably be Friday (Los Angeles time zone) before I can get back to it. :-(

**Comment by jethroppaPH** [comment] 2019-03-19 01:08
@jolars I tried your pkgbuild, but still I cannot install it. It generated an error, something in a subcommand of `ninja`. (I immediately closed the software manager, I forgot to copy the exact error).

**Comment by jolars** [comment] 2019-03-19 06:29
@jethroppaPH I don't know what's going on here, I did not write the PKGBUILD and I cannot access the report you have posted.

**Comment by jethroppaPH** [comment] 2019-03-20 01:09
I tried to install it several times last month, and yesterday I tried again using the pkgbuild you shared. This is the full output of the installation process of `v8` in my machine.

https://gist.github.com/jethroppaPH/6a40453cc262d32e99bdb3437accbefb

P.S. My first time using gist, hope you can access it.

**Comment by jolars** [comment] 2019-03-20 06:23
Thanks, I really don't know what's going on here. I suggest you post a comment over at <https://aur.archlinux.org/packages/v8/> or e-mail the maintainer of the AUR package.

**Comment by liuxch5** [comment] 2019-07-06 14:20
I solve this problem by this
sudo apt remove libv8*
sudo aptitude install libnode-dev
hope this could help you
