### ISSUE TITLE
failed to install V8 on FreeBSD

### ISSUE THREAD

**Issue by jszhao** [jeroen/V8#93] opened 2020-07-20 02:51 UTC
In R on FreeBSD, using `install.package("V8")`, I get the following error message. How to fix it? Thanks in advance.

```
* installing *source* package 'V8' ...
** package 'V8' successfully unpacked and MD5 sums checked
** using staged installation
Using PKG_CFLAGS=-I/usr/include/v8 -I/usr/include/v8-3.14
Using PKG_LIBS=-lv8 -lv8_libplatform
Found legacy version of libv8
** libs
rm -f V8.so legacy/V8.o legacy/v8_typed_array.o legacy/RcppExports.o
g++9 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -Ilegacy -I'/usr/local/lib/R/library/Rcpp/include' -DLIBICONV_PLUG -I/usr/local/include -isystem /usr/local/include  -DV8_DISABLE_DEPRECATIONS -fvisibility=hidden -fpic  -O2 -march=native -mtune=native -fPIC -c legacy/V8.cpp -o legacy/V8.o
g++9 -I"/usr/local/lib/R/include" -DNDEBUG -I/usr/include/v8 -I/usr/include/v8-3.14 -Ilegacy -I'/usr/local/lib/R/library/Rcpp/include' -DLIBICONV_PLUG -I/usr/local/include -isystem /usr/local/include  -DV8_DISABLE_DEPRECATIONS -fvisibility=hidden -fpic  -O2 -march=native -mtune=native -fPIC -c legacy/v8_typed_array.cpp -o legacy/v8_typed_array.o
legacy/v8_typed_array.cpp: In static member function 'static v8::Handle<v8::Value> {anonymous}::ArrayBuffer::V8New(const v8::Arguments&)':
legacy/v8_typed_array.cpp:105:18: error: 'class v8::Object' has no member named 'SetPointerInInternalField'; did you mean 'SetAlignedPointerInInternalField'?
  105 |     args.This()->SetPointerInInternalField(0, buf);
      |                  ^~~~~~~~~~~~~~~~~~~~~~~~~
      |                  SetAlignedPointerInInternalField
legacy/v8_typed_array.cpp: In static member function 'static v8::Handle<v8::Value> {anonymous}::TypedArray<TBytes, TEAType>::V8New(const v8::Arguments&)':
legacy/v8_typed_array.cpp:218:27: error: 'class v8::Object' has no member named 'GetPointerFromInternalField'; did you mean 'GetAlignedPointerFromInternalField'?
  218 |       void* buf = buffer->GetPointerFromInternalField(0);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                           GetAlignedPointerFromInternalField
legacy/v8_typed_array.cpp:231:27: error: 'class v8::Object' has no member named 'GetPointerFromInternalField'; did you mean 'GetAlignedPointerFromInternalField'?
  231 |       void* buf = buffer->GetPointerFromInternalField(0);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                           GetAlignedPointerFromInternalField
legacy/v8_typed_array.cpp:258:27: error: 'class v8::Object' has no member named 'GetPointerFromInternalField'; did you mean 'GetAlignedPointerFromInternalField'?
  258 |       void* buf = buffer->GetPointerFromInternalField(0);
      |                           ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      |                           GetAlignedPointerFromInternalField
gmake: *** [/usr/local/lib/R/etc/Makeconf:174: legacy/v8_typed_array.o] Error 1
ERROR: compilation failed for package 'V8'
* removing '/usr/local/lib/R/library/V8'
```

**Comment by jeroen** [comment] 2020-07-20 06:53
Duplicate of https://github.com/jeroen/V8/issues/90

Either install libv8 3.15 or try to install from this branch: `remotes::install_github("jeroen/V8@legacy318")`

**Closed by jeroen** 2020-07-20 06:53 UTC

**Comment by jeroen** [comment] 2020-07-20 06:59
Ideally we should ask @bradleythughes to buid nodejs with shared libv8, so you can link against that. This is how it is solved in Debian and Fedora.
